"""Initial migration

Revision ID: 840decf24d72
Revises: 
Create Date: 2024-12-25 04:57:17.536774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '840decf24d72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MSreplication_options')
    op.drop_table('spt_fallback_dev')
    op.drop_table('spt_fallback_db')
    op.drop_table('spt_fallback_usg')
    op.drop_table('spt_monitor')
    op.drop_table('KaggleTable')
    op.drop_table('MediumArticles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MediumArticles',
    sa.Column('Title', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Text', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('KaggleTable',
    sa.Column('Column1', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Column2', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Column3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Column4', sa.FLOAT(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('spt_monitor',
    sa.Column('lastrun', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('cpu_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('io_busy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_sent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connections', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_read', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_write', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_errors', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_usg',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_vstart', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('segmap', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lstart', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sizepg', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vstart', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_db',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_dbid', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('dbid', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=False)
    )
    op.create_table('spt_fallback_dev',
    sa.Column('xserver_name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('xdttm_ins', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xdttm_last_ins_upd', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('xfallback_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xfallback_drive', sa.CHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('low', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('high', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phyname', sa.VARCHAR(length=127, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False)
    )
    op.create_table('MSreplication_options',
    sa.Column('optname', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('value', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('major_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minor_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('install_failures', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
