"""Add alembic column to logs table

Revision ID: b8d83e00f699
Revises: bd034ca16e6c
Create Date: 2024-12-25 05:13:48.320256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d83e00f699'
down_revision: Union[str, None] = 'bd034ca16e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('alembic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'alembic')
    # ### end Alembic commands ###
